hw 3
Katerina2602/java-course pull request #4
Opened 2023-10-23 19:30 UTC by Katerina2602

2023-11-01 22:21 UTC, VictorMinsky requested changes

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task1/Alphabet.java
> +    private static final int LENGTH_ALPHABET = 25;
Константы стоит выносить в самый верх класса, выше конструкторов

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task1/Alphabet.java
> +    }
Используй пробелы, которые били бы код на логические секции, например:
```java
    public static Map<Character, Character> encryptAlphabet() {
        Map<Character, Character> emptyMap = new HashMap<>();
        int num = LENGTH_ALPHABET;
        char symbol = 'A';

        while (symbol != 'z' + 1) {
            emptyMap.put(symbol, (char) (symbol + num));
            symbol++;
            num = num - 2;

            if (num < -LENGTH_ALPHABET) {
                num = LENGTH_ALPHABET;
            }

            if (symbol == '[') {
                symbol = 'a';
            }
        }

        return emptyMap;
    }
```

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task1/Alphabet.java
> +            num = num - 2;
`num -= 2;`

2023-11-01 22:21 UTC, VictorMinsky commented on src/test/java/edu/hw3/task1/AtbashCipherTest.java
> +class AtbashCipherTest {
AtbashCipherTest -> AlphabetCipherTest

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task1/Alphabet.java
> +    }
В принципе нет смысла делать пустой конструктор, учитывая, что у тебя методы статик. Применимо к остальным заданиям в домашке

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task2/Bracket.java
> +                }
```java
                switch (str.charAt(i)) {
                    case '(' -> openBracket++;
                    case ')' -> closBracket++;
                }
```

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task3/WordFrequency.java
> +    public static Map<Object, Integer> countWord(List<Object> listOfObjects) {
Всё-таки у нас `Map<String, Integer>`

UPD перечитал условие. Не уверен, что вам показывали дженерики (aka параметризация), но здесь стоило использовать их. Например вот так:
```java
    public static<T> Map<T, Integer> countWord(List<T> listOfObjects) {
        Map<T, Integer> frequencyDictionary = new HashMap<>();
        for (int i = 0; i < listOfObjects.size(); i++) {
            frequencyDictionary.merge(listOfObjects.get(i), 1, Integer::sum);
        }
        return frequencyDictionary;
    }
```

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task3/WordFrequency.java
> +        for (int i = 0; i < listOfObjects.size(); i++) {
Воспользуйся рекомендацией идеи `'for' loop can be replaced with enhanced 'for' `

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task4/RomanNumerals.java
> +    public static String getRumanNumerals(int number) {
Roman

Вообще в задании написал пример названии функций (здесь `convertToRoman`). Стоит его придерживаться

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task4/RomanNumerals.java
> +        int arabicNumber = number;
А смысл? Назови аргумент сразу `arabicNumber`

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task5/ListContact.java
> +            String[] s = listContact[i].split(" ");
Раз используешь регулярку, то лучше уже `\\s+`

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task5/ListContact.java
> +        }
Тоже можно на `switch` заменить

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task5/ListContact.java
> +            sortListContact.sort((o1, o2) -> o1.lastname().compareTo(o2.lastname()));
`Can be replaced with 'Comparator.comparing'`

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task6/StockMarketImpl.java
> +        return stocks.poll();
Как вариант, но я всё же предполагаю, что надо просто вернуть эту акцию, не доставая из `stocks`. Поскольку джавакода у метода `Самая дорогая акция`, а не получить/купить

2023-11-01 22:21 UTC, VictorMinsky commented on src/main/java/edu/hw3/task8/BackwardIterator.java
> +        return element;
Я бы заинлайнил
```java
return list.get(cursor--);
```

2023-11-02 18:51 UTC, Katerina2602 commented on src/main/java/edu/hw3/task1/Alphabet.java
> +    }
Здравствуйте. Конструкторы не могу убрать, чекстайл тогда не пропускает
(Utility classes should not have a public or default constructor. [HideUtilityClassConstructor])

2023-11-02 19:08 UTC, Katerina2602 commented on src/main/java/edu/hw3/task4/RomanNumerals.java
> +        int arabicNumber = number;
тут тоже чекстайл ругается. Не разрешает изменять получаемые переменные

2023-11-02 23:35 UTC, VictorMinsky approved these changes
OK

Добавь меня, пожалуйста, в контрибьюторы репозитория, чтобы я мог резолвить треды с замечаниями.

Гайд -- https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

2023-11-02 23:35 UTC, VictorMinsky commented on src/main/java/edu/hw3/task1/Alphabet.java
> +    private static final int LENGTH_ALPHABET = 25;
Так и не пофиксили

2023-11-02 23:35 UTC, VictorMinsky commented on src/main/java/edu/hw3/task1/Alphabet.java
> +    }
Да, согласен, не прав

2023-11-02 23:35 UTC, VictorMinsky commented on src/main/java/edu/hw3/task4/RomanNumerals.java
> +        int arabicNumber = number;
Ох, забавный линтер, почему он так требует понятно, но тут примитив и он будет передаваться по значению, а не ссылке, жаль, что линтер это не понимает.

2023-11-02 23:35 UTC, VictorMinsky commented on src/main/java/edu/hw3/task5/ListContact.java
> +            case ("ASC"):
В скобки оборачивать особо смысла не было

2023-11-02 23:35 UTC, VictorMinsky commented on src/main/java/edu/hw3/task7/NullSafeComparator.java
> +
Вот тут пробел явно лишний, нет смысла делать пустую строку между объявлением метода и телом внутри

2023-11-03 08:39 UTC, Katerina2602 commented on src/main/java/edu/hw3/task1/Alphabet.java
> +    private static final int LENGTH_ALPHABET = 25;
Да, прошу прощения. Поправила, удалила конструктор, а когда чекстаил ругался, добавила конструктор автоматически и не проверила, что он добавился снова выше константы. Сейчас исправлю

2023-11-03 19:33 UTC, merged